spring.application.name=orderms-btgpactual

spring.mongodb.authentication-database=admin
spring.data.mongodb.auto-index-creation=true
spring.mongodb.host=localhost
spring.mongodb.database=btgpactualdb
spring.mongodb.username=admin
spring.mongodb.password=admin